# Generated by Django 5.2.12 on 2026-03-15 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        help_text="'federal' or state code like 'GA'", max_length=20
                    ),
                ),
                (
                    "form_number",
                    models.CharField(
                        help_text="e.g. '4797', 'Schedule D'", max_length=50
                    ),
                ),
                ("form_title", models.CharField(max_length=255)),
                (
                    "entity_types",
                    models.JSONField(
                        default=list, help_text="e.g. ['1120S', '1065', '1040']"
                    ),
                ),
                ("tax_year", models.IntegerField()),
                ("version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["jurisdiction", "form_number"],
                "unique_together": {
                    ("jurisdiction", "form_number", "tax_year", "version")
                },
            },
        ),
        migrations.CreateModel(
            name="TestScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scenario_name", models.CharField(max_length=255)),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("edge", "Edge Case"),
                            ("failure", "Failure"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("inputs", models.JSONField(default=dict)),
                ("expected_outputs", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_scenarios",
                        to="specs.taxform",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "scenario_name"],
            },
        ),
        migrations.CreateModel(
            name="FormRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(
                        help_text="Human-readable code like R001", max_length=20
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("calculation", "Calculation"),
                            ("classification", "Classification"),
                            ("routing", "Routing"),
                            ("validation", "Validation"),
                            ("conditional", "Conditional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True, default=dict, help_text="When does this rule apply?"
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Calculation or logic expression",
                    ),
                ),
                (
                    "inputs",
                    models.JSONField(
                        default=list, help_text="Array of fact_keys this rule reads"
                    ),
                ),
                (
                    "outputs",
                    models.JSONField(
                        default=list,
                        help_text="Array of fact_keys/line_numbers this rule writes",
                    ),
                ),
                ("precedence", models.IntegerField(default=0)),
                ("exceptions", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="specs.taxform",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "rule_id"],
                "unique_together": {("tax_form", "rule_id")},
            },
        ),
        migrations.CreateModel(
            name="FormLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_number", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                ("calculation", models.TextField(blank=True, default="")),
                ("source_facts", models.JSONField(default=list)),
                ("source_rules", models.JSONField(default=list)),
                (
                    "destination_form",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("input", "Input"),
                            ("calculated", "Calculated"),
                            ("subtotal", "Subtotal"),
                            ("total", "Total"),
                            ("informational", "Informational"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="specs.taxform",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "line_number"],
                "unique_together": {("tax_form", "line_number")},
            },
        ),
        migrations.CreateModel(
            name="FormFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fact_key",
                    models.CharField(help_text="snake_case identifier", max_length=100),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("choice", "Choice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "validation_rule",
                    models.TextField(
                        blank=True, help_text="e.g. 'must be >= 0'", null=True
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True, help_text="For choice-type facts", null=True
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="specs.taxform",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "fact_key"],
                "unique_together": {("tax_form", "fact_key")},
            },
        ),
        migrations.CreateModel(
            name="FormDiagnostic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diagnostic_id", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition", models.TextField(blank=True, default="")),
                ("message", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostics",
                        to="specs.taxform",
                    ),
                ),
            ],
            options={
                "ordering": ["diagnostic_id"],
                "unique_together": {("tax_form", "diagnostic_id")},
            },
        ),
    ]
