# Generated by Django 5.2.12 on 2026-03-30 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowAssertion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assertion_id",
                    models.CharField(
                        help_text="Human-readable code: TI001, FA001, RC001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "assertion_type",
                    models.CharField(
                        choices=[
                            ("table_invariant", "Table Invariant"),
                            ("flow_assertion", "Flow Assertion"),
                            ("reconciliation", "Reconciliation Check"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_types",
                    models.JSONField(
                        default=list,
                        help_text="e.g. ['1120S', '1065']. Empty = all entity types.",
                    ),
                ),
                (
                    "definition",
                    models.JSONField(
                        default=dict,
                        help_text="Machine-readable assertion parameters (type-specific)",
                    ),
                ),
                (
                    "bug_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What bug this would have caught, e.g. 'Mar 30 — 150DB tables wrong'",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "assertion_id"],
            },
        ),
    ]
