"""New AuthorityTopic definitions for broad federal coverage.

Each tuple: (topic_code, topic_name, parent_topic_code_or_None)
"""

TOPICS = [
    # Entity types
    ("s_corporation", "S Corporation", None),
    ("partnership", "Partnership", None),
    ("c_corporation", "C Corporation", None),
    ("individual", "Individual", None),

    # Filing
    ("filing_status", "Filing Status", "individual"),
    ("standard_deduction", "Standard Deduction", "individual"),
    ("itemized_deduction", "Itemized Deduction", "individual"),

    # Income / deduction categories
    ("rental_income", "Rental Income", None),
    ("passive_activity", "Passive Activity", None),
    ("at_risk", "At-Risk Rules", None),
    ("self_employment", "Self-Employment", None),
    ("fica", "FICA", None),
    ("estimated_tax", "Estimated Tax", None),
    ("qbi_deduction", "QBI Deduction (§199A)", None),
    ("education_credits", "Education Credits", None),
    ("premium_tax_credit", "Premium Tax Credit", None),
    ("like_kind_exchange", "Like-Kind Exchange (§1031)", None),
    ("installment_sale", "Installment Sale (§453)", None),
    ("involuntary_conversion", "Involuntary Conversion (§1033)", None),
    ("charitable", "Charitable Contributions", None),
    ("medical_expenses", "Medical Expenses", None),
    ("mortgage_interest", "Mortgage Interest", None),
    ("salt", "State and Local Taxes (SALT)", None),
    ("unicap", "Uniform Capitalization (UNICAP)", None),
    ("meals_entertainment", "Meals and Entertainment", None),
    ("built_in_gains", "Built-in Gains Tax", "s_corporation"),
    ("excess_passive_income", "Excess Passive Income", "s_corporation"),
    ("guaranteed_payments", "Guaranteed Payments", "partnership"),
    ("special_allocations", "Special Allocations", "partnership"),
    ("partner_basis", "Partner Basis", "partnership"),

    # Broad tax concepts
    ("gross_income", "Gross Income", None),
    ("adjusted_gross_income", "Adjusted Gross Income", None),
    ("taxable_income", "Taxable Income", None),
    ("trade_business_expenses", "Trade or Business Expenses", None),
    ("interest_deduction", "Interest Deduction", None),
    ("losses", "Losses", None),
    ("bad_debts", "Bad Debts", None),
    ("start_up_costs", "Start-Up Costs", None),
    ("amortization", "Amortization", None),
    ("home_office", "Home Office (§280A)", None),
    ("related_party", "Related Party Transactions", None),
    ("basis_rules", "Basis Rules", None),
    ("capital_asset", "Capital Asset Definition", None),
    ("farm_income", "Farm Income", None),
    ("ira", "Individual Retirement Accounts", None),
    ("cost_of_goods_sold", "Cost of Goods Sold", None),
    ("dividends_received", "Dividends Received Deduction", None),
    ("research_credit", "Research Credit", None),
    ("energy_credits", "Energy Credits", None),
    ("additional_medicare", "Additional Medicare Tax", None),
    ("niit", "Net Investment Income Tax", None),
    ("employee_expenses", "Employee Business Expenses", None),
    ("child_dependent_care", "Child and Dependent Care", None),
    ("casualty_theft", "Casualty and Theft Losses", None),
    ("farm_rental", "Farm Rental Income", None),
    ("corporate_tax", "Corporate Tax", "c_corporation"),
    ("partnership_allocations", "Partnership Allocations", "partnership"),
    ("partnership_distributions", "Partnership Distributions", "partnership"),
    ("partnership_contributions", "Partnership Contributions", "partnership"),
    ("partnership_transfers", "Partnership Interest Transfers", "partnership"),
    ("s_corp_basis", "S-Corp Shareholder Basis", "s_corporation"),
    ("s_corp_distributions", "S-Corp Distributions", "s_corporation"),
    ("schedule_k1", "Schedule K-1", None),
    ("form_1040", "Form 1040", "individual"),
    ("form_1065", "Form 1065", "partnership"),
    ("form_1120", "Form 1120", "c_corporation"),
    ("form_1120s", "Form 1120-S", "s_corporation"),
    ("form_7203", "Form 7203", "s_corporation"),
    ("form_8825", "Form 8825", None),
    ("form_1120h", "Form 1120-H", None),
    ("schedule_a", "Schedule A", "individual"),
    ("schedule_b_interest", "Schedule B", "individual"),
    ("schedule_c", "Schedule C", "individual"),
    ("schedule_d_1040", "Schedule D (1040)", "individual"),
    ("schedule_e", "Schedule E", "individual"),
    ("schedule_f", "Schedule F", "individual"),
    ("schedule_se", "Schedule SE", "individual"),
    ("form_2106", "Form 2106", None),
    ("form_2441", "Form 2441", None),
    ("form_3800", "Form 3800", None),
    ("form_4684", "Form 4684", None),
    ("form_4835", "Form 4835", None),
    ("form_6198", "Form 6198", None),
    ("form_6252", "Form 6252", None),
    ("form_8582", "Form 8582", None),
    ("form_8606", "Form 8606", None),
    ("form_8995", "Form 8995 / 8995-A", None),
    ("form_8863", "Form 8863", None),
    ("form_8962", "Form 8962", None),
    ("form_8959", "Form 8959", None),
    ("form_8960", "Form 8960", None),
    ("homeowners_association", "Homeowners Associations", None),
]
