# Generated by Django 5.2.12 on 2026-03-15 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("specs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFeedDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feed_code", models.CharField(max_length=100, unique=True)),
                ("feed_name", models.CharField(max_length=255)),
                ("jurisdiction_code", models.CharField(max_length=10)),
                (
                    "source_family",
                    models.CharField(
                        help_text="IRS_FORMS, IRS_MEF, GA_FORMS, etc.", max_length=50
                    ),
                ),
                ("base_url", models.TextField(blank=True, null=True)),
                (
                    "feed_type",
                    models.CharField(
                        choices=[
                            ("html_index", "HTML Index"),
                            ("pdf_list", "PDF List"),
                            ("xml_repo", "XML Repository"),
                            ("manual_upload", "Manual Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "refresh_frequency",
                    models.CharField(
                        help_text="daily, weekly, manual, seasonal", max_length=20
                    ),
                ),
                (
                    "parser_strategy",
                    models.CharField(
                        help_text="html_scrape, manual_clip, zip_unpack, pdf_register",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["feed_code"],
            },
        ),
        migrations.CreateModel(
            name="AuthoritySource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_code",
                    models.CharField(
                        help_text="e.g. IRC_1231, IRS_2025_4797_INSTR",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("code_section", "IRC Section"),
                            ("regulation", "Treasury Regulation"),
                            ("official_form", "Official Form"),
                            ("official_instruction", "Form Instructions"),
                            ("official_publication", "IRS Publication"),
                            ("official_notice", "IRS Notice"),
                            ("official_revenue_ruling", "Revenue Ruling"),
                            ("official_revenue_procedure", "Revenue Procedure"),
                            ("mef_schema", "MeF XML Schema"),
                            ("mef_business_rule", "MeF Business Rule"),
                            ("mef_release_memo", "MeF Release Memo"),
                            ("state_statute", "State Statute"),
                            ("state_regulation", "State Regulation"),
                            ("state_form", "State Form"),
                            ("state_instruction", "State Instructions"),
                            ("state_efile_spec", "State E-File Spec"),
                            ("state_vendor_guide", "State Vendor Guide"),
                            ("state_conformity_notice", "State Conformity Notice"),
                            ("internal_memo", "Internal Memo"),
                            ("internal_example", "Worked Example"),
                            ("internal_test_case", "Internal Test Case"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "source_rank",
                    models.CharField(
                        choices=[
                            ("controlling", "Controlling"),
                            ("primary_official", "Primary Official"),
                            ("implementation_official", "Implementation Official"),
                            ("internal_interpretation", "Internal Interpretation"),
                            ("reference_only", "Reference Only"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "jurisdiction_code",
                    models.CharField(help_text="FED, GA, CA, etc.", max_length=10),
                ),
                ("tax_year_start", models.IntegerField(blank=True, null=True)),
                ("tax_year_end", models.IntegerField(blank=True, null=True)),
                (
                    "entity_type_code",
                    models.CharField(
                        blank=True,
                        help_text="1040, 1120S, shared",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("title", models.TextField()),
                (
                    "citation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. IRC §1231(a)(1)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "issuer",
                    models.CharField(help_text="IRS, GA DOR, etc.", max_length=100),
                ),
                ("official_url", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("effective_date_start", models.DateField(blank=True, null=True)),
                ("effective_date_end", models.DateField(blank=True, null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("draft", "Draft"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("is_substantive_authority", models.BooleanField(default=False)),
                ("is_filing_authority", models.BooleanField(default=False)),
                ("is_internal_only", models.BooleanField(default=False)),
                ("requires_human_review", models.BooleanField(default=True)),
                (
                    "trust_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="sources.authoritysource",
                    ),
                ),
            ],
            options={
                "ordering": ["source_code"],
            },
        ),
        migrations.CreateModel(
            name="AuthorityFormLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_code",
                    models.CharField(
                        help_text="e.g. '4797', 'SCH_D', 'GA_600'", max_length=50
                    ),
                ),
                (
                    "form_part_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("line_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("governs", "Governs"),
                            ("informs", "Informs"),
                            ("validates", "Validates"),
                            ("mapping_only", "Mapping Only"),
                            ("overrides", "Overrides"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authority_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_links",
                        to="sources.authoritysource",
                    ),
                ),
            ],
            options={
                "ordering": ["form_code", "line_code"],
            },
        ),
        migrations.CreateModel(
            name="AuthorityExcerpt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "excerpt_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Part III instructions'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "location_reference",
                    models.CharField(
                        blank=True,
                        help_text="Page/section/line/XML path",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("excerpt_text", models.TextField()),
                ("summary_text", models.TextField(blank=True, null=True)),
                ("topic_tags", models.JSONField(blank=True, default=list)),
                (
                    "line_or_page_start",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "line_or_page_end",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("effective_year_start", models.IntegerField(blank=True, null=True)),
                ("effective_year_end", models.IntegerField(blank=True, null=True)),
                ("is_key_excerpt", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authority_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excerpts",
                        to="sources.authoritysource",
                    ),
                ),
            ],
            options={
                "ordering": ["authority_source", "excerpt_label"],
            },
        ),
        migrations.CreateModel(
            name="AuthorityTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic_code",
                    models.CharField(
                        help_text="e.g. 'depreciation', '1231'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("topic_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="sources.authoritytopic",
                    ),
                ),
            ],
            options={
                "ordering": ["topic_code"],
            },
        ),
        migrations.CreateModel(
            name="AuthorityVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_label",
                    models.CharField(help_text="e.g. 'TY2025 v3.0'", max_length=100),
                ),
                ("version_date", models.DateField(blank=True, null=True)),
                ("retrieval_url", models.TextField(blank=True, null=True)),
                ("retrieval_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "file_type",
                    models.CharField(
                        help_text="pdf, html, xml, zip, json", max_length=20
                    ),
                ),
                ("file_path", models.TextField(blank=True, null=True)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authority_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="sources.authoritysource",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JurisdictionConformitySource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jurisdiction_code",
                    models.CharField(help_text="GA, CA, etc.", max_length=10),
                ),
                ("tax_year", models.IntegerField()),
                ("federal_reference_note", models.TextField(blank=True, null=True)),
                (
                    "conformity_type",
                    models.CharField(
                        choices=[
                            ("rolling", "Rolling"),
                            ("static", "Static"),
                            ("partial", "Partial"),
                            ("decoupled", "Decoupled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authority_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conformity_records",
                        to="sources.authoritysource",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "jurisdiction conformity sources",
                "ordering": ["jurisdiction_code", "tax_year"],
            },
        ),
        migrations.CreateModel(
            name="RuleAuthorityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "support_level",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("interpretive", "Interpretive"),
                            ("implementation", "Implementation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("relevance_note", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authority_excerpt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rule_links",
                        to="sources.authorityexcerpt",
                    ),
                ),
                (
                    "authority_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_links",
                        to="sources.authoritysource",
                    ),
                ),
                (
                    "form_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authority_links",
                        to="specs.formrule",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="AuthoritySourceTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authority_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_topics",
                        to="sources.authoritysource",
                    ),
                ),
                (
                    "authority_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_topics",
                        to="sources.authoritytopic",
                    ),
                ),
            ],
            options={
                "unique_together": {("authority_source", "authority_topic")},
            },
        ),
    ]
