# Generated by Django 5.2.12 on 2026-03-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jurisdictionconformitysource",
            name="decoupled_items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured list of items where state diverges from federal. Each entry: {item, federal_treatment, state_treatment, authority_source_id, notes}",
            ),
        ),
    ]
