# Generated by Django 5.2.12 on 2026-07-08 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_jurisdictionconformitysource_decoupled_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRegisterItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_code', models.CharField(help_text='e.g. CR-2026-001', max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(help_text="What changed, in the authority's own terms (cite it).")),
                ('jurisdiction_code', models.CharField(default='US', help_text='US, GA, SC, ...', max_length=10)),
                ('tax_year', models.IntegerField(blank=True, help_text='The tax year the change first affects (year-keyed).', null=True)),
                ('detected_via', models.CharField(choices=[('manual_clip', 'Manual Clip'), ('checksum_diff', 'Checksum Diff'), ('feed_poll', 'Feed Poll')], default='manual_clip', max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('triaged', 'Triaged'), ('promoted', 'Promoted'), ('dismissed', 'Dismissed')], default='detected', max_length=20)),
                ('affected_forms', models.JSONField(blank=True, default=list, help_text='Form numbers the change touches, e.g. ["3115","4562"].')),
                ('affected_rule_ids', models.JSONField(blank=True, default=list, help_text='Optional: specific FormRule rule_ids implicated.')),
                ('is_substantive', models.BooleanField(blank=True, help_text='Triage call: does this require authoring? (null until triaged)', null=True)),
                ('triage_notes', models.TextField(blank=True, null=True)),
                ('promoted_work_order', models.CharField(blank=True, help_text='The WORK_ORDERS order id, e.g. WO-24.', max_length=30, null=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_items', to='sources.authoritysource')),
                ('authority_version', models.ForeignKey(blank=True, help_text='The new version whose checksum diff surfaced this (checksum_diff detection).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_items', to='sources.authorityversion')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_items', to='sources.sourcefeeddefinition')),
            ],
            options={
                'ordering': ['-detected_at', 'change_code'],
            },
        ),
    ]
