# Generated by Django 5.2.12 on 2026-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_changeregisteritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeregisteritem',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, help_text="Stable dedup key for automated detection: FR document_number, or 'checksum:<sha>' for the checksum arm.", max_length=120, null=True),
        ),
    ]
